# ?? ??? 8080?? ?????.
server:
  port: 8080

# ??? ?? ?? ?? ?????.
spring:
  # --- ?????? ?? ?? ---
  datasource:
    # DB ?? URL. ?? ?? docker-compose.yml? ?? ??(DB_URL)??? ?????.
    url: ${DB_URL}
    # DB ??? ??. docker-compose.yml? DB_USER??? ?????.
    username: ${DB_USER}
    # DB ????. docker-compose.yml? DB_PASSWORD??? ?????.
    password: ${DB_PASSWORD}
    # ??? JDBC ???? ???? ?????.
    driver-class-name: com.mysql.cj.jdbc.Driver

  # --- JPA ? Hibernate ?? ?? ---
  jpa:
    # ?????? ?? ?, ??? ???? DB ???? ???? ??? ??? ???? ?????.
    # (?? ??? 'update' ?? 'create'? ?? ?????.)
    hibernate:
      ddl-auto: update
    # JPA? ???? SQL ??? ??? ???? ??? ?????.
    show-sql: true
    # JPA ???? ??
    properties:
      # ???? SQL ??? ?? ?? ??????.
      hibernate:
        format_sql: true

# --- Spring Boot Actuator ?? ?? ---
management:
  # Actuator ????? ?? ??
  endpoints:
    web:
      exposure:
        # ??? ??? Actuator ?????? ?????.
        # Prometheus? ???? ??? ? ??? 'prometheus'? ??? ???? ???.
        include: "prometheus,health,info"

  # Actuator? ???? ??? ?? ??
  metrics:
    # ?? ???? ????? ??? ??? ?????.
    # ??? Grafana?? ?? ??????? ???? ??? ? ?????.
    tags:
      application: my-spring-app
